### ISSUE TITLE
Queries Inside Loops

### ISSUE THREAD

**Issue by richcallear** [Force-Config-Control/lightning-flow-scanner-core#25]
Hi - really useful tool - one key rule that I think is missing (or I missed it) is checking for flows that run queries within loops - better practice is to run a large query outside the loop and then use the "filter records" where necessary. Risk of queries within loops is that you'll run into the "too many SOQL queries" governer limit.

**Comment by RubenHalman** [comment]
Hi Richard. Thanks for your kind words. SOQL queries are actually a form of DML statements, so they will be flagged with the rule 'DML statements in a loop'. I think this can maybe be made clearer in the documentation, but if you use the vscode plugin it might also help explain.

**Comment by RubenHalman** [comment]
no thank you for helping me see the technical description is probably too technical haha, it's good that you ask questions. please continue to keep interacting with us on your experience!
