### ISSUE TITLE
Idea for new ruleset: identify copy of elements

### ISSUE THREAD

**Issue by fkramer690** [Force-Config-Control/lightning-flow-scanner-core#30]
I often see that elements are copied in the flow and the API Names are not corrected. This leads to a lot of copy_of_elements which is not clean. A check could help here.

**Comment by fkramer690** [comment]
Hey Ruben, below I created two screenshots for you. The original element is called flServices. When I clone it the new element is called Copy 1 of flService. 

<img width="341" alt="image" src="https://github.com/Force-Config-Control/lightning-flow-scanner-core/assets/87364496/cf5561b5-4be9-4265-b8cf-f6e5a652676c">

<img width="589" alt="image" src="https://github.com/Force-Config-Control/lightning-flow-scanner-core/assets/87364496/05b10a1f-24eb-48e3-8df2-2b5b93777ef9">

<img width="572" alt="image" src="https://github.com/Force-Config-Control/lightning-flow-scanner-core/assets/87364496/fc9366c2-8b91-4d1d-99c6-7c5b20b17d4b">

If you have multiple such copies of elements, checking the Toolbox Resource Tab and finding the correct one may be messy. Apart from that, this would also not be the way in apex to call a variable copy_1_of_accountList :-)

**Comment by RubenHalman** [comment]
this has been merged in the latest version of the core
